services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: creditveto
      POSTGRES_PASSWORD: creditveto
      POSTGRES_DB: creditveto
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - '6380:6379'

  backend:
    build: ./backend
    command: npm run start:prod
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=creditveto
      - POSTGRES_PASSWORD=creditveto
      - POSTGRES_DB=creditveto
      - JWT_SECRET=supersecretkey
      - JWT_REFRESH_SECRET=superrefreshsecret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AI_API_KEY=mock-or-real-key
    ports:
      - '4000:4000'
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4000
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  pgdata:
